#!/usr/bin/env bash
# Phase 60: Deploy OpenClaw — generate env + override, compose up, health checks. Idempotent.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

load_env
require_cmd lxc

GATEWAY_PORT="${OPENCLAW_PORT:-18789}"
BRIDGE_PORT="${OPENCLAW_BRIDGE_PORT:-18790}"
BIND_VALUE="${OPENCLAW_GATEWAY_BIND:-localhost}"

# Escape a value for env file: double-quote and escape backslash, double-quote, newline
env_escape() {
  local v="$*"
  v="${v//\\/\\\\}"
  v="${v//\"/\\\"}"
  v="${v//$'\n'/\\n}"
  printf '"%s"' "$v"
}

# 60.1 Build env file (non-secret from settings.env allow list + secrets + fixed vars)
# Allow list for settings: only pass through vars that are safe for VM (no host paths)
# All values are quoted/escaped so newlines and special chars in secrets are safe.
build_env_file() {
  local bind_val="${1:-localhost}"
  echo "# Generated by openclaw-lxd; do not edit in VM"
  echo "OPENCLAW_IMAGE=openclaw:local"
  echo "OPENCLAW_CONFIG_DIR=/opt/openclaw/config"
  echo "OPENCLAW_WORKSPACE_DIR=/opt/openclaw/workspace"
  echo "OPENCLAW_GATEWAY_BIND=$(env_escape "$bind_val")"
  echo "OPENCLAW_GATEWAY_PORT=${GATEWAY_PORT}"
  echo "OPENCLAW_BRIDGE_PORT=${BRIDGE_PORT}"
  # Secrets (already loaded from openclaw.secrets.env)
  [[ -n "${OPENCLAW_GATEWAY_TOKEN:-}" ]] && echo "OPENCLAW_GATEWAY_TOKEN=$(env_escape "$OPENCLAW_GATEWAY_TOKEN")"
  [[ -n "${CLAUDE_AI_SESSION_KEY:-}" ]] && echo "CLAUDE_AI_SESSION_KEY=$(env_escape "$CLAUDE_AI_SESSION_KEY")"
  [[ -n "${CLAUDE_WEB_SESSION_KEY:-}" ]] && echo "CLAUDE_WEB_SESSION_KEY=$(env_escape "$CLAUDE_WEB_SESSION_KEY")"
  [[ -n "${CLAUDE_WEB_COOKIE:-}" ]] && echo "CLAUDE_WEB_COOKIE=$(env_escape "${CLAUDE_WEB_COOKIE:-}")"
}

push_env_to_vm() {
  local bind_val="${1:-localhost}"
  local tmp
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' EXIT
  build_env_file "$bind_val" > "$tmp"
  lxc file push "$tmp" "$VM_NAME/opt/openclaw/openclaw.env"
  rm -f "$tmp"
  trap - EXIT
}

# 60.2 Compose override YAML (security hardening + allow unconfigured mode)
build_override_yml() {
  cat <<EOF
# Generated by openclaw-lxd; security hardening and configuration
services:
  openclaw-gateway:
    network_mode: host
    command: ["node", "dist/index.js", "gateway", "--bind", "lan", "--port", "18789", "--allow-unconfigured"]
    volumes:
      - /opt/openclaw/state:/home/node/.openclaw
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
EOF
}

push_override_to_vm() {
  local tmp
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' EXIT
  build_override_yml > "$tmp"
  lxc file push "$tmp" "$VM_NAME/opt/openclaw/repo/docker-compose.override.yml"
  rm -f "$tmp"
  trap - EXIT
}

# Deploy and run health check (return 0 if bind ok)
deploy_and_check() {
  local bind_val="${1:-localhost}"
  push_env_to_vm "$bind_val"
  push_override_to_vm

  # Stop any existing containers to avoid port conflicts
  log "Stopping any existing containers..."
  lxc_exec "$VM_NAME" bash -c 'cd /opt/openclaw/repo && docker compose --env-file /opt/openclaw/openclaw.env down' 2>/dev/null || true

  log "Starting containers..."
  lxc_exec "$VM_NAME" bash -c 'cd /opt/openclaw/repo && docker compose --env-file /opt/openclaw/openclaw.env up -d'

  # Wait for containers
  sleep 3
  if ! retry 15 2 lxc_exec "$VM_NAME" bash -c 'cd /opt/openclaw/repo && docker compose --env-file /opt/openclaw/openclaw.env ps --format json 2>/dev/null | grep -q "running"'; then
    log "WARNING: Container health check did not confirm running state"
  fi

  # Check: ports 18789 and 18790 are listening in VM (VM is isolated behind lxdbr0)
  # Retry because the gateway process may take a few seconds to bind the port
  local i
  for i in $(seq 1 10); do
    local ss_out
    ss_out="$(lxc_exec "$VM_NAME" ss -lntp 2>/dev/null)" || true
    if echo "$ss_out" | grep -qE ':(18789|18790)\s'; then
      return 0
    fi
    sleep 2
  done
  return 1
}

# Health: Check if gateway container is running and port is listening
http_ok() {
  # WebSocket server doesn't respond to HTTP GET, so check container status instead
  lxc_exec "$VM_NAME" docker ps --format '{{.Names}}' 2>/dev/null | grep -q 'openclaw-gateway' && \
  lxc_exec "$VM_NAME" ss -lntp 2>/dev/null | grep -q ":${GATEWAY_PORT}"
}

configure_gateway() {
  local container="repo-openclaw-gateway-1"

  # 1. Run setup (creates openclaw.json, workspace, sessions) — idempotent
  log "Running openclaw setup..."
  lxc_exec "$VM_NAME" docker exec "$container" node dist/index.js setup 2>/dev/null || true

  # 2. Interactive TUI: openclaw configure (credentials, devices, agent defaults)
  #    Requires -it for terminal interaction. User completes the wizard, then automation resumes.
  log "Launching interactive OpenClaw configure wizard..."
  log "Complete the wizard to set up credentials, devices, and agent defaults."
  log "(Press Ctrl+C to skip if already configured)"
  lxc exec "$VM_NAME" -- docker exec -it "$container" node dist/index.js configure || true

  # 3. Set gateway mode to local — idempotent
  lxc_exec "$VM_NAME" docker exec "$container" node dist/index.js config set gateway.mode local 2>/dev/null || true

  # 4. Run doctor --fix (creates credentials dir, fixes permissions) — idempotent
  lxc_exec "$VM_NAME" docker exec "$container" node dist/index.js doctor --fix 2>/dev/null || true

  # 5. Auto-approve ALL pending device pairing requests
  local pending
  pending="$(lxc_exec "$VM_NAME" docker exec "$container" cat /home/node/.openclaw/devices/pending.json 2>/dev/null)" || true
  if [[ -n "$pending" ]] && [[ "$pending" != "{}" ]]; then
    local request_ids
    request_ids="$(echo "$pending" | grep -oP '"requestId"\s*:\s*"\K[^"]+')" || true
    for rid in $request_ids; do
      log "Auto-approving pending device: $rid"
      lxc_exec "$VM_NAME" docker exec "$container" node dist/index.js devices approve "$rid" 2>/dev/null || true
    done
  fi

  # 6. Print dashboard URL with pairing token
  local dashboard_output
  dashboard_output="$(lxc_exec "$VM_NAME" docker exec "$container" node dist/index.js dashboard --no-open 2>/dev/null)" || true
  local token_url
  token_url="$(echo "$dashboard_output" | grep -oP 'http://\S+#token=\S+' | head -1)" || true
  if [[ -n "$token_url" ]]; then
    log "Dashboard URL: $token_url"
  fi
}

# --- Main ---
log "Deploying OpenClaw (bind=$BIND_VALUE)..."

# Ensure state dir exists and is writable by the container's node user (UID 1000)
lxc_exec "$VM_NAME" bash -c 'mkdir -p /opt/openclaw/state && chown 1000:1000 /opt/openclaw/state'

# Build Docker image if not already present
if ! lxc_exec "$VM_NAME" docker image inspect openclaw:local &>/dev/null; then
  log "Building OpenClaw Docker image (this may take a few minutes)..."
  if ! lxc_exec "$VM_NAME" bash -c 'cd /opt/openclaw/repo && docker build -t openclaw:local .'; then
    log "ERROR: Docker image build failed"
    exit 1
  fi
  log "Docker image build complete"
else
  log "Docker image openclaw:local already exists"
fi

if deploy_and_check "$BIND_VALUE"; then
  if http_ok; then
    log "Deploy and health checks OK (bind=$BIND_VALUE)"
    configure_gateway
    exit 0
  fi
  log "ERROR: Bind OK but HTTP check failed (bind=$BIND_VALUE)."
  exit 1
fi

# Fallback: try OPENCLAW_GATEWAY_BIND=loopback
log "Bind check failed with localhost; trying OPENCLAW_GATEWAY_BIND=loopback..."
if deploy_and_check "loopback"; then
  if http_ok; then
    log "Deploy and health checks OK (bind=loopback)"
    configure_gateway
    exit 0
  fi
  log "ERROR: Bind OK but HTTP check failed (bind=loopback)."
  exit 1
fi

log "ERROR: Containers not binding to 127.0.0.1 only. Check docker logs in VM: lxc exec $VM_NAME -- docker compose -f /opt/openclaw/repo/docker-compose.yml -f /opt/openclaw/repo/docker-compose.override.yml logs"
exit 1
